import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";


import {MicrophoneIcon,ViewGridIcon} from "@heroicons/react/solid";

import {SearchIcon} from "@heroicons/react/outline";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <header className="flex justify-between p-2 font-semibold bg-gray-200 text-gray-500">
        {/*left div */}
        <div className="flex space-x-4 items-center">
          <p>
            <a className="a_link" href="">Home</a>
          </p>
          <p>
            <a className="a_link" href="">About</a>
          </p>
        </div>

        {/*right div */}
        <div className="flex space-x-4 items-center">
          <p>
            <a className="a_link" href="">Gmail</a>
          </p>
          <p>
            <a className="a_link" href="">Images</a>
          </p>

          <ViewGridIcon className="h-9 w-9 p-1 rounded-full hover:bg-gray-300 cursor-pointer"/>
          {/* profile pic */}
          <Avatar url="/dileep.jpg"/>
        </div>
      </header>
      {/* Body */}

        <form className="flex flex-col items-center mt-30 flex-grow">
          <Image src="/logo.png" height="200" width="300"/>
          <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border-gray-200 p-4 items-center sm:max-w-xl lg:max-w-2xl">

            <SearchIcon className="h-5 mr-3 text-gray-500"/>
            <input type="text" className="flex-grow focus:outline-none"/>
            
            <MicrophoneIcon className="h-5 ml-3 text-gray-500"/>
          </div>
        </form>

      {/* Footer */}
    </div>
  );
}
