import Head from "next/head";

import Avatar from "../components/Avatar";

import {MicrophoneIcon,ViewGridIcon} from "@heroicons/react/solid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <header className="flex justify-between p-2 font-semibold bg-gray-200 text-gray-500">
        {/*left div */}
        <div className="flex space-x-4 items-center">
          <p>
            <a className="a_link" href="">Home</a>
          </p>
          <p>
            <a className="a_link" href="">About</a>
          </p>
        </div>

        {/*right div */}
        <div className="flex space-x-4 items-center">
          <p>
            <a className="a_link" href="">Gmail</a>
          </p>
          <p>
            <a className="a_link" href="">Images</a>
          </p>

          <ViewGridIcon className="h-9 w-9 p-1 rounded-full hover:bg-gray-300 cursor-pointer"/>
          {/* profile pic */}
          <Avatar url="/dileep.jpg"/>
        </div>
      </header>
      {/* Body */}

      {/* Footer */}
    </div>
  );
}
